name: Run tests
run-name: ${{ gitea.actor }} is running tests
on: [push]

jobs:
  Test:
    runs-on: self-hosted
    steps:
      - name: Install build dependencies
        run: apk add --no-progress -t .testing nodejs gtk+3.0-dev go
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run tidy to install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test -v ./...
      - name: Clean up build depdendencies
        run: apk del .testing
